spring:
  application:
    name: wise-task-profile
  datasource:
    url: jdbc:postgresql://localhost:5433/wise_task_profile
    username: wise_task_profile
    password: wise_task_profile
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

wavefront:
  application:
    name: wise-task-profile
    service: wise-task-profile


security:
  secret: secret

grpc:
  port: 6567
server:
  port: 8082

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql: TRACE
