spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/wise_task_profile
    username: wise_task_profile
    password: wise_task_profile
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true

security:
  secret: secret

grpc:
  port: 6567
server:
  port: 8082